# Generated by Django 5.2.8 on 2026-07-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media'),
        ),
    ]
